//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicManagementSystem.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public int Professional_ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public string AppointmentStartTime { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Comments { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Professional Professional { get; set; }
        public virtual Status_Type Status_Type { get; set; }
    }
}
