//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicManagementSystem.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Insurance
    {
        public int InsuranceID { get; set; }
        public int Customer_ID { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PCPName { get; set; }
        public string CustomerInsuranceNumber { get; set; }
        public string InsuranceType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Insurance_Type Insurance_Type { get; set; }
    }
}
