//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicManagementSystem.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional_Type
    {
        public Professional_Type()
        {
            this.Professionals = new HashSet<Professional>();
        }
    
        public int Professional_Type_ID { get; set; }
        public string Professional_Type_Desc { get; set; }
    
        public virtual ICollection<Professional> Professionals { get; set; }
    }
}
