//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicManagementSystem.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professional
    {
        public Professional()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Professional_Schedule = new HashSet<Professional_Schedule>();
        }
    
        public int Professional_ID { get; set; }
        public int Professional_Type_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Phone { get; set; }
        public string Professional_Identification_Number { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual Professional_Type Professional_Type { get; set; }
        public virtual ICollection<Professional_Schedule> Professional_Schedule { get; set; }
    }
}
