//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicManagementSystem.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status_Type
    {
        public Status_Type()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int StatusID { get; set; }
        public string StatusDesc { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
